export const AGENTS = [
  {
    id: 'sales',
    name: 'Sales Agent',
    emoji: '🤝',
    tagline: 'Close deals & generate leads',
    description: 'Expert in cold outreach, objection handling, pitch crafting, BANT qualification, and closing strategies. Your AI-powered top performer.',
    color: 'from-orange-500 to-red-500',
    bgGlow: 'rgba(249,115,22,0.15)',
    border: 'border-orange-500/30',
    accent: '#f97316',
    capabilities: ['Cold outreach scripts', 'Objection handling', 'Lead qualification', 'Pitch decks', 'Closing techniques'],
    placeholder: 'E.g. Write a cold email for my SaaS product targeting CTOs...',
  },
  {
    id: 'email',
    name: 'Email Agent',
    emoji: '📧',
    tagline: 'Craft perfect emails instantly',
    description: 'Drafts, replies, follow-up sequences, newsletters, and subject lines that get opened. Every email nailed on the first try.',
    color: 'from-blue-500 to-cyan-500',
    bgGlow: 'rgba(59,130,246,0.15)',
    border: 'border-blue-500/30',
    accent: '#3b82f6',
    capabilities: ['Cold outreach emails', 'Follow-up sequences', 'Newsletter writing', 'Subject line optimization', 'Thread summarization'],
    placeholder: 'E.g. Write a follow-up email after a demo that went well...',
  },
  {
    id: 'analyst',
    name: 'Data Analyst',
    emoji: '📊',
    tagline: 'Turn data into decisions',
    description: 'SQL queries, Python analysis, trend detection, KPI frameworks, and executive-ready reports. Makes data speak clearly.',
    color: 'from-violet-500 to-purple-600',
    bgGlow: 'rgba(139,92,246,0.15)',
    border: 'border-violet-500/30',
    accent: '#8b5cf6',
    capabilities: ['SQL query writing', 'KPI definition', 'Trend analysis', 'A/B test design', 'Dashboard planning'],
    placeholder: 'E.g. Analyze this monthly revenue data and find growth opportunities...',
  },
  {
    id: 'marketing',
    name: 'Marketing Agent',
    emoji: '🎯',
    tagline: 'Campaigns that convert',
    description: 'Full-funnel strategy, social media campaigns, SEO, paid ads copy, and brand positioning. Think CMO, available 24/7.',
    color: 'from-pink-500 to-rose-500',
    bgGlow: 'rgba(236,72,153,0.15)',
    border: 'border-pink-500/30',
    accent: '#ec4899',
    capabilities: ['Campaign strategy', 'Social media content', 'SEO/SEM', 'Ad copywriting', 'Brand messaging'],
    placeholder: 'E.g. Create a 30-day Instagram campaign for a fitness app launch...',
  },
  {
    id: 'hr',
    name: 'HR Agent',
    emoji: '💼',
    tagline: 'Build & manage great teams',
    description: 'Job descriptions, interview frameworks, performance reviews, HR policies, and conflict resolution. Your people operations partner.',
    color: 'from-teal-500 to-emerald-500',
    bgGlow: 'rgba(20,184,166,0.15)',
    border: 'border-teal-500/30',
    accent: '#14b8a6',
    capabilities: ['Job descriptions', 'Interview questions', 'Performance reviews', 'HR policies', 'Onboarding plans'],
    placeholder: 'E.g. Write a job description for a Senior Full Stack Engineer...',
  },
  {
    id: 'content',
    name: 'Content Writer',
    emoji: '📝',
    tagline: 'Words that engage & convert',
    description: 'Blog posts, social captions, video scripts, whitepapers, and landing page copy. Every format, every voice, every platform.',
    color: 'from-yellow-500 to-amber-500',
    bgGlow: 'rgba(234,179,8,0.15)',
    border: 'border-yellow-500/30',
    accent: '#eab308',
    capabilities: ['SEO blog posts', 'Social captions', 'Video scripts', 'Product copy', 'Ghostwriting'],
    placeholder: 'E.g. Write a 1000-word SEO blog post about AI productivity tools...',
  },
  {
    id: 'support',
    name: 'Customer Support',
    emoji: '🛠️',
    tagline: 'Resolve issues, delight customers',
    description: 'Response templates, de-escalation scripts, FAQ creation, SLA policies, and support SOPs. Turn complaints into loyalty.',
    color: 'from-sky-500 to-blue-600',
    bgGlow: 'rgba(14,165,233,0.15)',
    border: 'border-sky-500/30',
    accent: '#0ea5e9',
    capabilities: ['Response templates', 'De-escalation scripts', 'FAQ writing', 'CSAT strategy', 'Support SOPs'],
    placeholder: 'E.g. Write a response for a customer angry about a delayed refund...',
  },
  {
    id: 'finance',
    name: 'Finance Agent',
    emoji: '💰',
    tagline: 'Financials, forecasts & strategy',
    description: 'Budgets, P&L analysis, financial modeling, cash flow forecasting, and fundraising guidance. Your on-demand CFO.',
    color: 'from-green-500 to-emerald-600',
    bgGlow: 'rgba(34,197,94,0.15)',
    border: 'border-green-500/30',
    accent: '#22c55e',
    capabilities: ['Budget planning', 'Cash flow analysis', 'Financial modeling', 'Startup fundraising', 'Pricing strategy'],
    placeholder: 'E.g. Create a 12-month financial projection for a SaaS startup...',
  },
  {
    id: 'legal',
    name: 'Legal Agent',
    emoji: '⚖️',
    tagline: 'Contracts, compliance & clarity',
    description: 'NDA drafting, privacy policies, employment agreements, IP guidance, and GDPR compliance. Legal clarity without the hourly bill.',
    color: 'from-slate-500 to-gray-600',
    bgGlow: 'rgba(100,116,139,0.15)',
    border: 'border-slate-500/30',
    accent: '#64748b',
    capabilities: ['NDA & contracts', 'Privacy policies', 'Employment agreements', 'IP guidance', 'GDPR compliance'],
    placeholder: 'E.g. Draft an NDA for sharing product specs with a potential partner...',
  },
  {
    id: 'product',
    name: 'Product Manager',
    emoji: '🚀',
    tagline: 'Ship great products, faster',
    description: 'PRDs, user stories, roadmaps, OKRs, competitive analysis, and go-to-market plans. Product leadership on demand.',
    color: 'from-indigo-500 to-violet-600',
    bgGlow: 'rgba(99,102,241,0.15)',
    border: 'border-indigo-500/30',
    accent: '#6366f1',
    capabilities: ['PRD writing', 'User stories', 'Roadmap planning', 'OKR setting', 'Go-to-market strategy'],
    placeholder: 'E.g. Write a PRD for a mobile notifications feature...',
  },
]
